#==================================================================================================
# Xcodegen documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme
#==================================================================================================

#==================================================================================================
name: SampleInvestments
#==================================================================================================

settings:
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  bundleIdPrefix: com.comitando.
  xcodeVersion: "13.0"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "13.0"
  
#==================================================================================================
targets:
#==================================================================================================

  SampleInvestments:

    platform: iOS
    type: application
    
    sources:
      - path: SampleApp

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: SampleApp
      INFOPLIST_FILE: SampleApp/Info.plist
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: ""
      PROVISIONING_PROFILE: "Wildcard"
  
  SampleInvestmentsTests:

    platform: iOS
    type: bundle.unit-test
    
    sources:
      - path: SampleAppTests
    
    dependencies:
      - target: SampleInvestments

#==================================================================================================
schemes:
#==================================================================================================

  Sample:
    build:
      targets:
        SampleInvestments: [run, test]
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      config: Debug
    test: 
      config: Debug
      gatherCoverageData: true
      coverageTargets: 
        - SampleInvestments
      targets:
        - SampleInvestmentsTests