name: SampleTests

settings:
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  bundleIdPrefix: com.comitando.
  xcodeVersion: "13.0"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "13.0"

packages:
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    from: 1.9.0

targets:

  SampleTests:

    platform: iOS
    type: application
    
    sources:
      - path: SampleApp
    
    dependencies:
      - target: DesignSystem
      - target: Models

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: SampleApp
      INFOPLIST_FILE: SampleApp/Info.plist
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: ""
      PROVISIONING_PROFILE: "Wildcard"
  
  SampleTestsTests:

    platform: iOS
    type: bundle.unit-test
    
    sources:
      - path: SampleAppTests
        excludes:
          - "__Snapshots__"
          - "**/__Snapshots__"
    
    dependencies:
      - target: SampleTests
      - target: DesignSystem
      - target: Models
      - package: SnapshotTesting  
  
  DesignSystem:
    templates:
      - Framework
    dependencies:
      - target: Models
  
  Models:
    templates:
      - Framework
    
schemes:

  Sample:
    build:
      targets:
        SampleTests: [run, test, archive]
      parallelizeBuild: true
      buildImplicitDependencies: true
    archive:
      config: Release
    run:
      config: Debug
    test: 
      config: Debug
      gatherCoverageData: true
      coverageTargets: 
        - SampleTests
      targets:
        - SampleTestsTests

#========================== PART 2 
targetTemplates:
  Framework:
    platform: iOS
    type: framework
    sources: 
      - path: Libraries/${target_name}
    info:
      path: Libraries/${target_name}/Info.plist
