
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!

workspace 'SampleInvestments'

target 'SampleInvestments' do

  pod 'SwiftLint'
  pod 'SwiftGen', '6.5.1'

  target 'SampleInvestmentsTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'SampleInvestments', :path => './'
end