
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

inhibit_all_warnings!
use_frameworks!

workspace 'MVC'

target 'MVC' do

  pod 'SwiftLint'
  pod 'SwiftGen', '6.5.1'

  target 'MVCTests' do
      #pod 'Dependency', '~> 1.0.0'
  end
end

target 'SampleApp' do
  project 'SampleApp/SampleApp'
  pod 'MVC', :path => './'
end